# Generated by Django 4.2 on 2023-04-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_remove_subjectprofessor_date_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_units',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
