# Generated by Django 4.2 on 2023-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_subjects_alter_professor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
    ]
