# Generated by Django 4.2 on 2023-04-20 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('schedule_days', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
                ('time', models.CharField(choices=[('08:00 - 09:30', '08:00 - 09:30'), ('09:30 - 11:00', '09:30 - 11:00'), ('11:00 - 12:30', '11:00 - 12:30'), ('13:00 - 14:30', '13:00 - 14:30'), ('14:30 - 16:00', '14:30 - 16:00'), ('16:00 - 17:30', '16:00 - 17:30'), ('17:30 - 19:00', '17:30 - 19:00'), ('19:00 - 20:30', '19:00 - 20:30'), ('20:30 - 22:00', '20:30 - 22:00')], max_length=20, null=True)),
            ],
        ),
    ]
