# Generated by Django 4.2 on 2023-04-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslots', models.TextField()),
                ('professors_assigned', models.TextField()),
                ('students_assigned', models.TextField()),
                ('subjects', models.TextField()),
            ],
        ),
    ]
