# Generated by Django 4.2 on 2023-04-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_schedule_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='timeslots',
        ),
        migrations.AddField(
            model_name='schedule',
            name='time',
            field=models.CharField(choices=[('08:00 - 09:30', '08:00 - 09:30'), ('09:30 - 11:00', '09:30 - 11:00'), ('11:00 - 12:30', '11:00 - 12:30'), ('13:00 - 14:30', '13:00 - 14:30'), ('14:30 - 16:00', '14:30 - 16:00'), ('16:00 - 17:30', '16:00 - 17:30'), ('17:30 - 19:00', '17:30 - 19:00'), ('19:00 - 20:30', '19:00 - 20:30'), ('20:30 - 22:00', '20:30 - 22:00')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_days',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True),
        ),
    ]
