# Generated by Django 4.2 on 2023-04-20 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_professor_subjects_alter_professor_age'),
        ('schedules', '0002_schedule_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='professor.professor'),
        ),
    ]
