# Generated by Django 4.2 on 2023-04-18 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_remove_subjectprofessor_date_updated_and_more'),
        ('professor', '0002_professor_subjects_alter_professor_age'),
        ('students', '0009_student_mi'),
        ('schedules', '0003_remove_schedule_timeslots_schedule_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='professors_assigned',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='students_assigned',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='subjects',
        ),
        migrations.CreateModel(
            name='ScheduleSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
                ('student_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('professor_assigned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='professors',
            field=models.ManyToManyField(related_name='ScheduleProfessor_professor_assigned', through='schedules.ScheduleProfessor', to='professor.professor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(related_name='SheduleStudent_student_assigned', through='schedules.ScheduleStudent', to='students.student'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.ManyToManyField(related_name='ScheduleStudent_subject_assigned', through='schedules.ScheduleSubject', to='subjects.subject'),
        ),
    ]
