# Generated by Django 4.2 on 2023-04-20 14:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_address_alter_student_birthdate_and_more'),
        ('schedules', '0003_schedule_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='schedules', through='schedules.ScheduleStudent', to='students.student'),
        ),
    ]
