# Generated by Django 4.2 on 2023-04-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_remove_schedule_professors_assigned_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulesubject',
            old_name='date_joined',
            new_name='date_added',
        ),
    ]
