# Generated by Django 4.2 on 2023-04-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_schedulestudent_schedule_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('1st sem', 'First Semester'), ('2nd sem', 'Second Semester')], default='1st sem', max_length=10),
        ),
    ]
