# Generated by Django 4.2 on 2023-04-19 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_rename_date_joined_schedulesubject_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
