# Generated by Django 4.2 on 2023-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_full_name'),
        ('subjects', '0008_remove_subjectprofessor_date_updated_and_more'),
        ('schedules', '0006_schedule_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulesubject',
            old_name='subject',
            new_name='subject_assigned',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(related_name='ScheduleStudent_student_assigned', through='schedules.ScheduleStudent', to='students.student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subjects',
            field=models.ManyToManyField(related_name='ScheduleSubject_subject_assigned', through='schedules.ScheduleSubject', to='subjects.subject'),
        ),
    ]
