# Generated by Django 4.2 on 2023-04-19 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_remove_subjectprofessor_date_updated_and_more'),
        ('schedules', '0007_rename_subject_schedulesubject_subject_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subjects',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ScheduleSubject_subject_assigned', to='subjects.subject'),
        ),
    ]
