# Generated by Django 4.1.7 on 2023-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_2x2 photo submitted_student_goodmorale_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='studentType',
            field=models.CharField(choices=[('Undergraduate', 'Undergraduate')], max_length=15, null='Choose'),
            preserve_default='Choose',
        ),
        migrations.AddField(
            model_name='student',
            name='suffix',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
