# Generated by Django 4.2 on 2023-04-10 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_birthdate_student_studenttype_student_suffix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GoodMorale_done',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='PSA_done',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='TwoByTwo_done',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='form137_done',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
