# Generated by Django 4.2 on 2023-04-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_remove_subjectprofessor_date_updated_and_more'),
        ('students', '0005_alter_student_goodmorale_done_alter_student_psa_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, through='subjects.SubjectStudent', to='subjects.subject'),
        ),
    ]
