# Generated by Django 4.2 on 2023-04-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_student_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
    ]
