# Generated by Django 4.2 on 2023-04-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=80),
        ),
    ]
