# Generated by Django 4.2 on 2023-04-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_first_name_alter_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mi',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='suffix',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
