# Generated by Django 4.2 on 2023-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_address_alter_student_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
    ]
